### ISSUE TITLE
Refresh image

### ISSUE THREAD

**Issue by dmzio** [stevevega/docker-compass#2]
On pulls Docker complains as 
>Image docker.io/stevevega/compass:latest uses outdated schema1 manifest format. Please upgrade to a schema2 image for better future compatibility. More information at https://docs.docker.com/registry/spec/deprecated-schema-v1/

could you rebuild image, please?

**Comment by stevevega** [comment]
Thanks @dmzio, done!

**Comment by dmzio** [comment]
Thanks!
